// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbOeaeeRHIh4N-BC82gQmdVEs3kJnJqYo',
    appId: '1:636388040860:web:1aeeac13cbf30dfc2acd59',
    messagingSenderId: '636388040860',
    projectId: 'meau-backend',
    authDomain: 'meau-backend.firebaseapp.com',
    storageBucket: 'meau-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVhjraAIuL5IoDOP1jgN1656gnygIcucA',
    appId: '1:636388040860:android:1daac81bfe16739e2acd59',
    messagingSenderId: '636388040860',
    projectId: 'meau-backend',
    storageBucket: 'meau-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6AmDTv0BaGAQuAwcds3MT7-H4zCRQ8Uk',
    appId: '1:636388040860:ios:232f0751f56810682acd59',
    messagingSenderId: '636388040860',
    projectId: 'meau-backend',
    storageBucket: 'meau-backend.appspot.com',
    iosClientId: '636388040860-btrgv2l675lg87o51q6gk2a0nt3aph2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6AmDTv0BaGAQuAwcds3MT7-H4zCRQ8Uk',
    appId: '1:636388040860:ios:232f0751f56810682acd59',
    messagingSenderId: '636388040860',
    projectId: 'meau-backend',
    storageBucket: 'meau-backend.appspot.com',
    iosClientId: '636388040860-btrgv2l675lg87o51q6gk2a0nt3aph2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
